### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by grylls** [riverrun/genxword#21]
Getting this error when using python 3.7.4.

**Comment by riverrun** [comment]
First of all, sorry for the delay in getting back to you.

Is this using Windows? Does the error output give you any other information (for example, where the ImportError is)?

**Comment by grylls** [comment]
Np, Yeah in windows.

(base) C:\Users\dubey>genxword word_list.txt n
Traceback (most recent call last):
  File "c:\users\dubey\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dubey\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dubey\Anaconda3\Scripts\genxword.exe\__main__.py", line 5, in <module>
  File "c:\users\dubey\anaconda3\lib\site-packages\genxword\cli.py", line 21, in <module>
    from .control import _, Genxword
  File "c:\users\dubey\anaconda3\lib\site-packages\genxword\control.py", line 24, in <module>
    from .calculate import Crossword, Exportfiles
  File "c:\users\dubey\anaconda3\lib\site-packages\genxword\calculate.py", line 22, in <module>
    import gi
  File "c:\users\dubey\anaconda3\lib\site-packages\gi\__init__.py", line 42, in <module>
    from . import _gi
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by grylls** [comment]
Trying to install gi/pgi , getting error

dubey\\AppData\\Local\\Temp\\pip-install-omgeg1nw\\pgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\dubey\\AppData\\Local\\Temp\\pip-install-omgeg1nw\\pgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\dubey\AppData\Local\Temp\pip-install-omgeg1nw\pgi\
    Complete output (21 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dubey\AppData\Local\Temp\pip-install-omgeg1nw\pgi\setup.py", line 18, in <module>
        import pgi
      File "C:\Users\dubey\AppData\Local\Temp\pip-install-omgeg1nw\pgi\pgi\__init__.py", line 10, in <module>
        from .importer import require_version, get_required_version
      File "C:\Users\dubey\AppData\Local\Temp\pip-install-omgeg1nw\pgi\pgi\importer.py", line 15, in <module>
        from .clib.gir import GIRepository
      File "C:\Users\dubey\AppData\Local\Temp\pip-install-omgeg1nw\pgi\pgi\clib\gir\__init__.py", line 8, in <module>
        from .giargument import GIArgument
      File "C:\Users\dubey\AppData\Local\Temp\pip-install-omgeg1nw\pgi\pgi\clib\gir\giargument.py", line 9, in <module>
        from ..glib import gboolean, gint8, guint8, gint16, guint16, gint32, guint32
      File "C:\Users\dubey\AppData\Local\Temp\pip-install-omgeg1nw\pgi\pgi\clib\glib.py", line 16, in <module>
        _glib = find_library("glib-2.0")
      File "C:\Users\dubey\AppData\Local\Temp\pip-install-omgeg1nw\pgi\pgi\clib\_utils.py", line 99, in find_library
        _internal[name] = cdll.LoadLibrary(_so_mapping[name])
      File "C:\Users\dubey\Anaconda3\lib\ctypes\__init__.py", line 442, in LoadLibrary
        return self._dlltype(name)
      File "C:\Users\dubey\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by riverrun** [comment]
Could you try running `pip install PyGObject` and see if that works?

**Comment by grylls** [comment]
nope its already there

**Comment by grylls** [comment]
nope its already there 
Requirement already satisfied: PyGObject in c:\users\dubey\anaconda3\lib\site-packages (3.30.5)

**Comment by riverrun** [comment]
Do have Gtk installed? If it is installed, is it a recent version?

I think you will need to install a fairly recent version of Gtk. There seem to be quite a few guides online for installing Gtk on Windows - I cannot recommend any of them in particular because I do not use Windows.

**Comment by grylls** [comment]
Installed it today.
But same error

**Comment by riverrun** [comment]
I don't know what to suggest next. I will add a note to the README explaining that it is clearly 'difficult' to get this working on Windows at the moment.

There is an issue (#22) about allowing users to install just the command-line interface, and if and when I have the time to do that, then you will be able to install that on Windows.

**Comment by grylls** [comment]
Thanks for reverting back.

**Comment by sumedhsingh** [comment]
Yep, stuck on the same error. I installed msys to install most of the dependencies but now I am stuck on this import gi error.
