### ISSUE TITLE
Genxword-gtk not working on debian 

### ISSUE THREAD

**Issue by koenwybo** [riverrun/genxword#7]
Genxword 1.0.9 and version 0.95 in terminal and genxwordt-gtk version python and python3 makes a grid but does not save clues and keys.
Only version 0.55 works correctly. 
Is there a way I can debug this to make the newer versions work?

**Comment by koenwybo** [comment]
output of genxword version 1.0.9 started with command: genxword -m -o "joehoe" lijst.txt p

Traceback (most recent call last):
  File "/usr/local/bin/genxword", line 9, in <module>
    load_entry_point('genxword==1.0.9', 'console_scripts', 'genxword')()
  File "/usr/local/lib/python3.4/dist-packages/genxword/control.py", line 153, in main
    gen.gengrid(args.output, args.saveformat)
  File "/usr/local/lib/python3.4/dist-packages/genxword/control.py", line 138, in gengrid
    exp.create_files(name, saveformat, lang, message, self.Thai)
  File "/usr/local/lib/python3.4/dist-packages/genxword/calculate.py", line 273, in create_files
    self.export_pdf(name, '_grid.pdf', lang, RTL)
  File "/usr/local/lib/python3.4/dist-packages/genxword/calculate.py", line 246, in export_pdf
    clues = self.wrap(self.legend(lang))
  File "/usr/local/lib/python3.4/dist-packages/genxword/calculate.py", line 320, in legend
    outStrA, outStrD = '\nClues\n{}\n'.format(lang[0]), '{}\n'.format(lang[1])
IndexError: list index out of range

**Comment by koenwybo** [comment]
SOLVED : removed all the translation files from /usr/local/share/locale/ and the terminal-version works again. GTK crashes when trying to save. 
This is a rather radical solution ...

**Comment by riverrun** [comment]
Thanks for reporting the issue.
I'll look into it and get back to you later on this week.

**Comment by riverrun** [comment]
I think there was a small error in the Dutch translation, which I've fixed.
Version 1.1 should be OK.
Let me know if you have any problems.
